[package]
name = "hash_finder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.6"
rayon = "1.7.0"
clap = "4.3.0"
assert_cmd = "2.0.11"